#!/bin/bash
#
# dell1600n-net-scan
# Starts and stops the dell1600n-net-scan service
#
# chkconfig: 2345 12 88
# description: dell1600n-net-scan allows you to scan from a Dell 1600n (or another supported printer) to the directory of your choice
# pidfile: /var/run/dell1600n-net-scan.pid
### BEGIN INIT INFO
# Provides: $dell1600n-net-scan
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/csh-scan/dell1600n-net-scan.pl
DAEMON_OPTS='--listen mfp.csh.rit.edu --name CSH --multi-session --resolution 300 --option pdf'
SCAN_DIR=/tmp/scans
USER=www-data
NAME=dell1600n-net-scan
DESC="Dell 1600n Network Scanning Service"

test -f $DAEMON || exit 0

# Make sure the scans directory exists
if [ -d "$SCAN_DIR" ]; then
	mkdir $SCAN_DIR
fi

set -e

case "$1" in
  start)
 echo -n "Starting $DESC: "
 start-stop-daemon --start --quiet --chuid $USER --chdir $SCAN_DIR --background --make-pidfile --pidfile /var/run/$NAME.pid \
  --exec /usr/bin/perl --startas $DAEMON -- $DAEMON_OPTS
 echo "$NAME."
 ;;
  stop)
 echo -n "Stopping $DESC: "
 # --quiet
 start-stop-daemon --stop --signal 15 --pidfile /var/run/$NAME.pid \
  --exec /usr/bin/perl --startas $DAEMON -- $DAEMON_OPTS
 echo "$NAME."
 ;;
  restart|force-reload)
 echo -n "Restarting $DESC: "
 start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
  --exec /usr/bin/perl --startas $DAEMON -- $DAEMON_OPTS
 sleep 1
 start-stop-daemon --start --quiet --chuid $USER --chdir $SCAN_DIR --background --make-pidfile 
  --exec /usr/bin/perl --startas $DAEMON -- $DAEMON_OPTS
 echo "$NAME."
 ;;
  *)
 N=/etc/init.d/$NAME
 # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
 echo "Usage: $N {start|stop|restart|force-reload}" >&2
 exit 1
 ;;
esac

exit 0